### ISSUE TITLE
Email al creador de un grupo

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/institutos#12]
Enviar un email al creador de un grupo cuando alguien haya creado una materia impartida para el grupo

**Comment by joycon** [comment]
Alguna idea de como sacar el id del creador (instance.creador) dentro de una función findById, ahora mismo esta instancia devuelve "function () { [ code native ] }" como era de esperar por la relación del belongsTo, mi idea era sacar un context de la función finById de Grupo, he estado probando fields filters e include filters pero no lo saca (https://loopback.io/doc/en/lb3/Fields-filter.html)

```js

'use strict';

var config = require('../../server/config.local.js');
var path = require('path');

module.exports = function(Materiaimpartida) {
    
    // cargamos script para poder ejecutar modelos relacionados
    var app = require('../../server/server.js');
    
    Materiaimpartida.afterRemote('create', function(context, materiaimpartida, next) {
	console.log('> materiaimpartida.afterRemote triggered');
        
        // nombre de la materia
        var idMateria = context.args.data.materia; 
        var Materia = app.models.Materia;
        Materia.findById(idMateria, function(err, instance) {
            var nombreMateria = "Nombre de la materia: " + instance.nombre;
            console.log(nombreMateria);
            
            // nombre del grupo
            var idGrupo = context.args.data.grupo;
            var Grupo = app.models.Grupo;
            Grupo.findById(idGrupo, function(err, instance) {
                var nombreGrupo = "Nombre del grupo: " + instance.nombre;
                var creadorGrupo = "Creador del grupo: " + instance.creador;
                console.log(creadorGrupo);
                
                console.log("Materia: "+nombreMateria+" Grupo: "+nombreGrupo+" Creador: "+creadorGrupo);
            });
 
        });
    });
};

```

**Comment by albsierra** [comment]
Deberías echar un vistazo a [Métodos añadidos con las relaciones](http://loopback.io/doc/en/lb3/BelongsTo-relations.html#methods-added-to-the-model).
Creo que lo que intentas es tan fácil como hacer:
```
var grupo = materiaimpartida.grupo;
var materia = materiaimpartida.materia;

```
que son las formas síncronas de recoger el _grupo_ y la _materia_ relacionadas con una _materiamatriculada_.

No lo he probado, porque estoy con las fixtures, pero creo que así podría funcionar:
```
'use strict';

module.exports = function(Materiaimpartida) {

	Materiaimpartida.afterRemote('create', function(context, materiaimpartida, next) {
		console.log('> materiaimpartida.afterRemote triggered');

		var materia = materiaimpartida.materia;
		var grupo = materiaimpartida.grupo;
		var creador = grupo.userId;


		console.log("Materia: " + materia.nombre + " Grupo: " + grupo.nombre + " Creador: " + creador.apellidos);
	});
};

```
También puedes intentar la forma asíncrona de recibir esas mismas variables, pero, se complicaría un poco más.

**Comment by joycon** [comment]
Este tipo de construcción fue lo primero que probé, pero para mi sorpresa me devolvía un indefinido, y termine con findById, sacando las relaciones como puse en el código, pero claro cuando llegue al creador, no vi la forma de poder sacar el context de un findById.

**Comment by albsierra** [comment]
Acabo de subir un nuevo commit.

El problema es que el nombre de las relaciones en Loopback no puede ser el mismo que el de la tabla que relaciona. Por eso, a todas las relaciones que tenían el mismo nombre que la tabla les he añadido Id.

Ahora sí funcionan correctamente.

Te paso el código de la forma asíncrona:
```

'use strict';

module.exports = function(Materiaimpartida) {

	Materiaimpartida.afterRemote('create', function(context, materiaimpartida, next) {
		console.log('> materiaimpartida.afterRemote triggered');
		materiaimpartida.materiaId(function(err, materia) {
			if (err) throw err;
			materiaimpartida.grupoId(function(err, grupo) {
				if (err) throw err;
				grupo.userId(function(err, creador) {
					if (err) throw err;

					console.log("Materia: " + materia.nombre + " Grupo: " + grupo.nombre + " Creador: " + creador.apellidos);
					next();
				})

			})

		})
	});
};

```
Ya solo quedaría enviar el email antes de hacer el next()

**Comment by joycon** [comment]
Muy buena :100:  , esto es una de esas cosas que después es imposible olvidar :+1:
