### ISSUE TITLE
Crear rol coordinador

### ISSUE THREAD

**Issue by armero1989** [2DAW-2Mares/institutos#18]
Crear rol coordinador  para enviar correo al coordinador

**Comment by armero1989** [comment]
Rol Coordinador creado`

**Comment by armero1989** [comment]
[https://github.com/2DAW-2Mares/institutos/commit/4ba07ae3406e6f7e3f3397468c3d7168ee4b5d7e](url)

**Comment by armero1989** [comment]
Rol coordinador creado

[http://github.com/2DAW-2Mares/institutos/commit/4ba07ae3406e6f7e3f3397468c3d7168ee4b5d7e](url)

**Comment by albsierra** [comment]
Esta solución no es válida.

Debes fijarte en la solución que ha dado @Salva79 a un problema parecido: alguien será coordinador si su centro está verificado.
Este es el [commit](https://github.com/2DAW-2Mares/institutos/commit/413c8a9dbd5c19ab137b5549d6fb2831a6f1f812) de @Salva79 .

**Comment by armero1989** [comment]
Creo que ya esta <a href="http://github.com/2DAW-2Mares/institutos/commit/b21741421bacc21b9d5ef1265649bea328e152cd">el commit es este</a>
