### ISSUE TITLE
Crear Rol Tutor

### ISSUE THREAD

**Issue by armero1989** [2DAW-2Mares/institutos#19]
Consiste en crear un rol Tutor

**Comment by Angel-Urrea** [comment]
#19 Creado el rol Tutor. A falta de realizar otro Issue donde un alumno tutorado tenga que verificar vía e-mail, la petición de tutorización por parte del tutor. En otras palabras, un tutor solicita a un alumno ser tutorado (por dicho tutor). Este alumno dará el visto bueno con un e-mail que le llegará con dicha petición.

**Comment by albsierra** [comment]
Correcto!!
