### ISSUE TITLE
POST /matriculas

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/institutos#26]
Sólo se podrán crear matrículas en grupos verificados.

**Comment by rubenff14** [comment]
He realizado un disparador que antes de guardar el registro en la BD, comprueba que el grupo está verificado, si el grupo esta verificado permite la inserción de la matrícula.

**Comment by albsierra** [comment]
Bien. Lo único es que a la función de callback en el _before save_ de **matricula.js** no hace falta ponerle nombre y, menos aún, _removeUnwantedField()_
