### ISSUE TITLE
Validar grupo

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/institutos#6]
El coordinador del centro puede validar los grupos creados en su centro.

**Comment by MarianoSaura** [comment]
Hecho

**Comment by MarianoSaura** [comment]
Lo subo directamente por aquí, porque si lo ago por git la voy a borrar cosas que no debo (He tocado ficheros que no deberia y lo malo esque no recuerdo cuantos han sido. Por esa razón ante la duda lo comento).

Grupo.validar_grupo = function(idgrupo, accessToken, cb) {


        if (!accessToken) {             
            var err = new Error('No existe el usuario');
            err.statusCode = 404;
            return cb(err);

        }
       
        var Anyoescolar = app.models.Anyoescolar;
        var Centro = app.models.Centro;
        Grupo.findById(idgrupo , function(err, grupo) {
            Anyoescolar.findById(grupo.id , function(err, anyoescolar) {
                Centro.findById(anyoescolar.centro, function(err, centro){
                    console.log("------------> "+centro.coordinador+" ------->"+accessToken.userId);
                    if (accessToken.userId === centro.coordinador){
                    
                        if (err) {
                            var err = new Error('No existe ningún grupo con ese id');
                            err.statusCode = 404;
                            return cb(err);
                        }
                        grupo.updateAttribute('verificado', true, function(err, grupo) {
                            if (err) {
                                var err = new Error('Error al verificar el grupo');
                                err.statusCode = 404;
                                return cb(err);
                            }
                            console.log('> grupo verificado correctamente');
                            return cb(null, 'grupo verificado correctamente')
                        });
                        
                    }
                })
            })
        })
       
    };

    Grupo.remoteMethod(
        'validar_grupo', {
            description: 'Valida un grupo. Lo debe hacer un coordinador',
            accepts: [{
                arg: 'idgrupo',
                type: 'integer',
                required: true
            },{
                arg: 'access_token',
                type: 'object',
                required: true,
                http: function(ctx) {
                    var req = ctx && ctx.req;
                    var accessToken = req && req.accessToken;

                    return accessToken;
                }
            },],
            returns: {
                arg: 'msg',
                type: 'string'
            },
            http: {
                path: '/validar-grupo',
                verb: 'put'
            },
        }
    );
