### ISSUE TITLE
Correo al creador del Grupo

### ISSUE THREAD

**Issue by albsierra** [2DAW-2Mares/institutos#7]
Una vez que el coordinador del Centro ha validado el grupo, se debe enviar un email al creador del grupo.

**Comment by MarianoSaura** [comment]
Hola buenas noches, Como puedo resolver esto si la tabla intermedia Materiaimpartida esta vacia??

**Comment by MarianoSaura** [comment]
//Una vez que el coordinador del Centro ha validado el grupo, se debe enviar un email al creador del grupo.
// grupo -- materiaImpartida -- Usuario
//		id Grupo            id docente
	//Necesito el disparador https://loopback.io/doc/en/lb2/Model-hooks.html
	Grupo.afterRemote('before Validate', function(context, grupo, next) {
	
		var html = '<h1>El grupo ' + grupo.nombre + ' se ha validado</h1>';

		grupo.grupoId(function(err, grupo) {
			if (err) throw err
			grupo.creadorId(function(err, docente) {
				if (err) throw err;
				docente.userId(function(err, creador) {
					if (err) throw err;

					console.log(" Creador: " + creador.email);
					next();
				})

			})
		})


		/*Grupo.app.models.Email.send({
			to: //Necesito el email del creador del grupo
			from: config.emailDs.transports[0].auth.user,
			subject: 'Nuevo grupo registrado',
			text: 'El grupo ' + grupo.nombre + ' se ha registrado en la web',
			html: html
		}, function(err, mail) {
			if (err) throw err;
			console.log('email sent!');
			next();
		});*/
	});

**Comment by albsierra** [comment]
Lo primero en lo que debes tener cuidado es en la elección de la documentación. Mejor la documentación de [Loopback 3](https://loopback.io/doc/en/lb3/index.html). Entre otras cosas, porque, según la documentación, 

> Model hooks are deprecated, except for afterInitialize.

Es decir, no se aconseja el uso de los _Model hooks_.

Actualmente, el atributo que identifica al propietario (coordinador) del grupo es _userId_. Con él podrás conseguir su email.

**Comment by MarianoSaura** [comment]
Hecho

**Comment by MarianoSaura** [comment]
Grupo.afterRemote('validar_grupo', function(context, grupo, next) {

       // for(var prop in context.args) console.log(context.args);
        //console.log(context.args.idgrupo+" - "+context.args.access_Token.userId)

        var Usuario = app.models.Usuario;
        Grupo.findById(context.args.idgrupo , function(err, grupo) {

            var html = '<h1>El grupo ' + grupo.nombre + ' se ha validado</h1>';

            Usuario.findById(grupo.creador , function(err, user) {

                Grupo.app.models.Email.send({
                    to: user.email,
                    from: config.emailDs.transports[0].auth.user,
                    subject: 'Nuevo grupo registrado',
                    text: 'El grupo ' + grupo.nombre + ' se ha validado',
                    html: html
                }, function(err, mail) {
                    if (err) throw err;
                    console.log('email sent!');
                    next();

                });
            });      
        });
         
    });
